import { paths } from './paths'
import { components } from './components'

export const swaggerDocument = {
  openapi: '3.0.1',
  info: {
    version: '1.0.0-alpha',
    title: 'IV CESINF ExpressJS Workshop',
    description: 'ExpressJS 101 worshop aimed to introduce the most basic concepts about this server module.',
    termOfService: '',
    contact: {
      name: 'Dailos Rafael Díaz Lara',
      url: 'https://linkedin.com/in/ddialar'
    }
  },
  paths,
  components: {
    securitySchemes: {
      Bearer: {
        type: 'apiKey',
        in: 'header',
        name: 'Authorization',
        description: 'For accessing the API a valid JWT token must be passed in all the queries in the \'Authorization\' header.\n\nA valid JWT token is generated by the API and retourned as answer of a call to the route /login giving a valid user & password.\n\nThe following syntax must be used in the \'Authorization\' header:\n\nBearer xxxxxx.yyyyyyy.zzzzzz'
      }
    },
    schemas: { ...components }
  }
}

export const swaggerOptions = {}
