// NOTE Import paths and components once they are defined
// import { paths } from './paths'
// import { components } from './components'

export const swaggerDocument = {
  openapi: '3.0.1',
  // TODO Define the most basic information for Swagger
  info: {
    version: '1.0.0-alpha',
    title: 'IV CESINF ExpressJS Workshop',
    description: 'ExpressJS 101 worshop aimed to introduce the most basic concepts about this server module.',
    termOfService: '',
    contact: {
      name: 'Dailos Rafael Díaz Lara',
      url: 'https://linkedin.com/in/ddialar'
    }
  },
  // TODO Define the paths that will be handled by Swagger
  paths: {},
  components: {
    // TODO Define the security requirements applied to different endpoints Swagger
    securitySchemes: {
      Bearer: {
        type: 'apiKey',
        in: 'header',
        name: 'Authorization',
        description: 'For accessing the API a valid JWT token must be passed in all the queries in the \'Authorization\' header.\n\nA valid JWT token is generated by the API and retourned as answer of a call to the route /login giving a valid user & password.\n\nThe following syntax must be used in the \'Authorization\' header:\n\nBearer xxxxxx.yyyyyyy.zzzzzz'
      }
    },
    // TODO Define the data structures that will be handled by Swagger
    schemas: {}
    // NOTE Components will be here once they are defined
    // schemas: { ...components }
  }
}

// NOTE Additional options to customize Swagger
export const swaggerOptions = {}
